### PR TITLE
Rename draw_select to selection_inflate_enabled, fixed option_offset, renamed inflate to highlight, added menu shadow

### PR DESCRIPTION
**Pull request by ppizarror**

### CODE REVIEW

**Comment by anxuae** [comment]
The term "inflate" is maybe not so clear for users?

**Comment by ppizarror** [comment]
> The term "inflate" is maybe not so clear for users?

I remember you added this feature. What else name we could use?

**Comment by anxuae** [comment]
That is true, and I have no really better name. Maybe `highlight`? But it is quite long..

**Comment by ppizarror** [comment]
> That is true, and I have no really better name. Maybe `highlight`? But it is quite long..
> ok keep it ;-)

highlight seems ok

**Comment by ppizarror** [comment]
Solved issue #126, also added support for offset and scrolls.
The only issue I found happens when setting a large option offset, for example 5000, the scrollbar starts at zero (that's ok) but each time user loops through the menu the X scroll restores. Added a gif.
@anxuae  can you test the new offset feature? thanks!

epic

**Comment by anxuae** [comment]
I integrate a little change on selector widget by removing a space.
Now its is like other widget, if a space is need, it shall be put in the label of the widget.

**Pull request merged**
