### PR TITLE
Add a documentation

### PR DESCRIPTION
**Pull request by anxuae**
This is the first structure for the documentation on Read The Docs platform (#118 ).
Need to merge before to continue.
I will rework some docstrings.

### CODE REVIEW

**Comment by ppizarror** [comment]
Nice! Hope it's compatible with #132

**Comment by anxuae** [comment]
This is a first draft : https://pygame-menu.readthedocs.io/en/docs
Lots of work remains.

The README.md will be trash so don't need to update it anymore. I will use a sphinx extension called `autodoc` to automatically extract doc from python code.

**Comment by ppizarror** [comment]
> This is a first draft : https://pygame-menu.readthedocs.io/en/docs
> Lots of work remains.
> 
> The README.md will be trash so don't need to update it anymore. I will use a sphinx extension called `autodoc` to automatically extract doc from python code.

I'm crying, this is a major new feature for v3 😍

**Comment by ppizarror** [comment]
Can I merge?

**Comment by anxuae** [comment]
Yes

**Pull request merged**
