### PR TITLE
Remove unsued variable, clean code

### PR DESCRIPTION
**Pull request by anxuae**
The `_last_selected_surface ` was never used
Use the tuple comparison to simplify the code

### CODE REVIEW

**Comment by anxuae** [comment]
Other proposal: put `center_content=True` by default in `Menu()` ?

**Comment by ppizarror** [comment]
> center_content=True

agree! this can be added in this PR

**Comment by anxuae** [comment]
Other proposal: add a theme that use the`LeftArrowSelection` ?

@eforgacs, maybe we can add your theme as a BLACK one?

**Comment by eforgacs** [comment]
> Other proposal: add a theme that use the`LeftArrowSelection` ?
> 
> @eforgacs, maybe we can add your theme as a BLACK one?

That sounds good to me @anxuae !

**Comment by ppizarror** [comment]
Merging 😄

**Pull request merged**
