### PR TITLE
Fix call to callback in text_input

### PR DESCRIPTION
**Pull request by anxuae**
The call to ``change()`` was missing.

### CODE REVIEW

**Comment by anxuae** [comment]
Also, the ``maxsize`` parameter of the ``TextInput``is difficult
 to use, I think that a ``wax width`` which correspond to the max widget size should be more useful,

**Comment by ppizarror** [comment]
> Also, the `maxsize` parameter of the `TextInput`is confusing with `maxlength`.
> Proposal for better understanding:
> 
> * rename `maxlength` -> `maxchar` representing the max number of characters (keeping `maxlength` is also understandable)
> * rename `maxsize` -> `maxwidth` representing the max width of the widget
> 
> With the current implementation, it is difficult to avoid menu window overflow because the width depends on the rendering of the chosen font, not the length of the string. The `maxwidth` should be compared with `_rect.width` after rendering instead of `len(self._input_string)`.
> 
> What do you think?

I'm agree with name change, but `maxwidth` and `_rect.width` is a little bit difficult to implement because you should change dynamically the 'maxsize' variable with each char the user types (if not the ellipsis will not work) or the system that does the word-cut (`self._update_renderbox`) must be changed completely.

If you wish you can create a PR or push here to change the variable names.

**Comment by anxuae** [comment]
In fact after several test, it is really difficult implement that.

**Comment by ppizarror** [comment]
> In fact after several tests, it is really difficult implement that.
> This will require to save the size of each character in a list using `self._font.size(char)[0]`.

Yep, you could store the size of each character into a dict, if the char size does not exist then it's calculated. To resolve this *issue* we could draw the ellipsis after the label (left ellipsis) and the right ellipsis is in the right side of the _rect(). Dynamically after each input `_update_renderbox()` must update the inner `self._renderbox` depending on how many chars have been entered. That can be done as:

```
total_size = 0
for k in *rendering box*:
   total_size += self._charsize[k]
   if total_size > max_rendering_size: # The string at k exceeds the length of the input
        update_render_box_up_to_k()
        if there_is_more_string_after_k:
                draw_right_ellipsis_close_to_right_side_of_rect
        ..... other asserts
```

In fact this is similar to the mouse event I added, `_update_cursor_mouse()` determines at which **k** char the accumulated size of the substring exceeds the relative mouse click position, and then updates the cursor position to the *k* char.

Anyway, I think that the changing size of the input, is not nice, but it's functional. Selector width changes too, and buttons.... If you ask me I don't like at all the style of the menu, it's functional but not professional Maybe after v2.0.0 we can create a much more *professional* UI, letting the user to choose from a bunch of styles, maybe the input size can be normalized, etc...

If you agree I'll push this PR to master and then release v2.0.0

**Comment by anxuae** [comment]
I'm agree with you, maybe those improvements can be done in the future.
You can push the PR and release the v2.0.0.

thanks
anxuae

**Pull request merged**
