### PR TITLE
Create left arrow selection.

### PR DESCRIPTION
**Pull request by eforgacs**

### CODE REVIEW

**Comment by eforgacs** [comment]
> The description of the class LeftArrowSelection must be changed. It's the same from highlight. Also the names of the parameters. arrow size can be in the constructor

Ah, you're right. Resubmitting with changes

**Comment by ppizarror** [comment]
How do you use margin? As far as I see the size of your selection box is the same as the widget. So margin should be something like (0, arrow_size, 0, 0). Also self.margin_x, self.margin_y can be deleted

**Comment by eforgacs** [comment]
> How do you use margin? As far as I see the size of your selection box is the same as the widget + the size of the left arrow. So margin should be something like (0, arrow_size, 0, 0). Also self.margin_x, self.margin_y can be deleted. Also border width can be removed too

Good call. Removed self.margin_x, self.margin_y. and self.border_width.

**Comment by ppizarror** [comment]
thanks!

**Pull request merged**
