### PR TITLE
Fix update list dropselect

### LINKED ISSUE #340: dropselect doesn't update index correctly
**Environment information**
Describe your environment information, such as:
- SO: linux
- python version: v3.8
- pygame version: v2.0.1
- pygame-menu version: v4.0.6

**Describe the bug**
Updating a `dropselect` item list with fewer elements might raise an exception when the selected index is higher than new list lenght. In the following example the button deletes the item selected, but fails if it is the last item.

**To Reproduce**
```
import pygame, pygame_menu

SCREENWIDTH  = 800
SCREENHEIGHT = 480

def main():
    pygame.init()

    surface = pygame.display.set_mode((SCREENWIDTH, SCREENHEIGHT))

    def test_1(select):
        sVal = select.get_value()
        items = select._items
        items.pop(items.index(sVal[0]))
        #select._index = -1
        select.update_items(items)
        select.make_selection_drop()

    menu = pygame_menu.Menu('Test', SCREENWIDTH, SCREENHEIGHT,
                            theme = pygame_menu.themes.THEME_DARK,
                            onclose = pygame_menu.events.RESET,
                            touchscreen = False,
                            joystick_enabled = False,
                            mouse_enabled = True,
                            )

    S1 = menu.add.dropselect('Subject Id', items=[('a',),('b',),('c',),('d',),('e',),('f',)], dropselect_id='s0')
    menu.add.button('One',test_1, S1)

    # Allows menu to be run
    menu.mainloop(surface)
    print(menu.get_input_data())
    return

if __name__ == "__main__":
    main()
```

**Expected behavior**
The documentation says that if the new list has different size than the actual list, the new index will be -1, but that is not happening.
https://pygame-menu.readthedocs.io/en/4.0.6/_modules/pygame_menu/widgets/widget/dropselect.html#DropSelect.update_items
As a workaround, uncommenting the line (15) that sets `_index` to -1, helps to avoid the exception.

Also, I don't understand what `select.make_selection_drop()` but there is an exception if I don't call it.

**Additional context**
I belived this verification
https://github.com/ppizarror/pygame-menu/blob/3d8ef71b882a6e7bcbe7299af8d16fbcc0875d8f/pygame_menu/widgets/widget/dropselect.py#L1000
is intended to be before
https://github.com/ppizarror/pygame-menu/blob/3d8ef71b882a6e7bcbe7299af8d16fbcc0875d8f/pygame_menu/widgets/widget/dropselect.py#L992

### PR DESCRIPTION
**Pull request by ppizarror**
- Fixes #340.

### CODE REVIEW

**Comment by yagui** [comment]
if `make_selection_drop` needs to be called after updating the items in the selector, can it be called from the `update_items` method itself? That way one doesn't need to call it, which is a bit intuitive for me.

**Comment by ppizarror** [comment]
> if `make_selection_drop` needs to be called after updating the items in the selector, can it be called from the `update_items` method itself? That way one doesn't need to call it, which is a bit intuitive for me.

Yep, I'll add that

**Comment by ppizarror** [comment]
It should not call automatically that function, such as **kwargs are empty (the style of the dropbox). Thus, calling automatically that method is not a good idea, and the method must be manually updated by the user.

**Comment by ppizarror** [comment]
Anyway I think a parameter such as update_items(items, make_selection_box=True, **kwargs) might be a nice addition, let me know what do you think @yagui

**Comment by yagui** [comment]
It might be better in the sense that you only need to call this method and not the other one.
From the 'user point of view' what it makes sense to me is that the `update_items` method should handle everything, and I would assume the only parameter needed is the new item list.
I don't understand yet if you always need to call the the `make_selection_drop` method or it is only in specific situations.
Either calling an extra method or having to add a parameter doesn't feel smooth to me.
I think maybe, if the need to call this method (or adding the parameter) cannot be avoided, there should be a reference in the documentation. At the beginning I though I was using this method wrongly. 
It is important to remark that you and this library are awesome. Thanks!!

**Comment by ppizarror** [comment]
> It might be better in the sense that you only need to call this method and not the other one.
> From the 'user point of view' what it makes sense to me is that the `update_items` method should handle everything, and I would assume the only parameter needed is the new item list.
> I don't understand yet if you always need to call the the `make_selection_drop` method or it is only in specific situations.
> Either calling an extra method or having to add a parameter doesn't feel smooth to me.
> I think maybe, if the need to call this method (or adding the parameter) cannot be avoided, there should be a reference in the documentation. At the beginning I though I was using this method wrongly.
> It is important to remark that you and this library are awesome. Thanks!!

There were some design problems regarding ``make_selection_drop``, first it needed the theme to be set, thus, it could not be called within the constructor as the widget must have been already appended to the Menu. Second, after each item update the theme style disappeared if calling the make method again.

So, I've decided to move all ``scrollbar`` style properties to the class constructor, thus, no **kwargs needed. Also, new widget events were needed to automatically create the selection drop style after the widget was appended to the Menu. For making the drop the widget must be appended to the menu as the drop box (frame) needs the reference of the menu surface (called the world).

#344 implements these changes, and the function no longer is needed to be manually called after updating the lists.

**Pull request merged**
