### PR TITLE
Image Support

### PR DESCRIPTION
**Pull request by ppizarror**
#34, #134

image

### CODE REVIEW

**Comment by ppizarror** [comment]
Any ideas, suggestions @anxuae @eforgacs ?

**Comment by ppizarror** [comment]
Next step is to create `Background` class that can accept an image (BaseImage) or a color. This added to the Themes class, when filling the menu surface background can do:

1. surface.fill(background color) if color
2. surface.fill(image), image can be stretched to the menu height/width or it can be repeated using a `for` instruction.

All widgets will accept "background" object given by Menu class as default, but user can change the background image as well. So introducing this, with minimal effort user can write images as background for all the widgets. The architecture of `pygame-menu` can handle this new feature with minimal changes.

**Comment by eforgacs** [comment]
> Any ideas, suggestions @anxuae @eforgacs ?

Wow, this is a pretty cool addition! Since we're adding images in, do you think it would be possible to add maybe an arrow selector that shows what item is being chosen (instead of the rectangular selection indicator)? People could make the arrow be whatever they want for their game, related to the theme of their game.

**Comment by ppizarror** [comment]
> > Any ideas, suggestions @anxuae @eforgacs ?
> 
> Wow, this is a pretty cool addition! Since we're adding images in, do you think it would be possible to add maybe an arrow selector that shows what item is being chosen (instead of the rectangular selection indicator)? People could make the arrow be whatever they want for their game, related to the theme of their game.

Can you provide a graphical example of this? How that arrow may be seen?
Yes. In fact, due to the current architecture, adding new "selection boxes" can be done quite easy because widget makes the selection box.

**Comment by eforgacs** [comment]
image

Here's basically what I am trying to make in one of my projects. I've got most of it working already, of course the columns and rows were a welcome addition! ;)
What I'd like to do is add that arrow to the left that shows which option is being chosen.

**Comment by ppizarror** [comment]
> image
> 
> Here's basically what I am trying to make in one of my projects. I've got most of it working already, of course the columns and rows were a welcome addition! ;)
> What I'd like to do is add that arrow to the left that shows which option is being chosen.

Ah yes, it can be archieved easily. I had the next idea: Divide the widget/ into

```
widgets/core/
widgets/selectors/
widgets/widget/
```

Inside widgets/core/ will exist widget.py, selector.py

Selector.py provides Selection class. That accepts the widget surface and returns a selected widget surface.

The first selector may be RectSelector that only draws a rectangle.

If you want to add an LeftArrowSelector it would be nice! I can code the rest, you add the leftarrowselector :)

@anxuae, do you like this approach?

**Comment by eforgacs** [comment]
> > image
> > Here's basically what I am trying to make in one of my projects. I've got most of it working already, of course the columns and rows were a welcome addition! ;)
> > What I'd like to do is add that arrow to the left that shows which option is being chosen.
> 
> Ah yes, it can be archieved easily. I had the next idea: Divide the widget/ into
> 
> ```
> widgets/selectors/
> widgets/widget/
> selector.py
> widget.py
> ```
> 
> Selector.py provides Selection class. That accepts the widget surface and returns a selected widget surface.
> 
> The first selector may be RectSelector that only draws a rectangle.
> 
> If you want to add an LeftArrowSelector it would be nice! I can code the rest, you add the leftarrowselector :)
> 
> @anxuae, do you like this approach?

That sounds great! I'd be glad to make the LeftArrowSelector :) Let's also wait to hear back from @anxuae as well.

**Comment by ppizarror** [comment]
I think I'm going to merge and continue discussing in #160

**Pull request merged**
