### PR TITLE
Removed text menu, improved widget position update

### PR DESCRIPTION
**Pull request by ppizarror**
As discused in #121. Things to fix:
- The actual computation of y position considers all the widgets have the same height
- I'll add a parameter to define the margin of the text, if None use the margin of the widgets

### CODE REVIEW

**Comment by ppizarror** [comment]
@anxuae created `max_char` on label to create a multi line text. The only issue here is as lines cannot been selected, the scroll does not work with arrow keys. See scroll example:

a6be5b91-1ee4-48c2-b497-8fb8b1b10781

I suggest to scroll also with re pag / av pag keys

**Comment by ppizarror** [comment]
> @anxuae created `max_char` on label to create a multi line text. The only issue here is as lines cannot been selected, the scroll does not work with arrow keys. See scroll example:
> 
> a6be5b91-1ee4-48c2-b497-8fb8b1b10781
> 
> I suggest to scroll also with re pag / av pag keys

Also, is `mouse_enabled` is False the scroll will not work

**Comment by ppizarror** [comment]
Improved text wrap using `textwrap` library from python core.

image

**Comment by ppizarror** [comment]
Introduced a major change in how position of widgets are stored: now each menu has a key dict containing the position of each widget. If the surface is rendered the position are stored. It's faster than before. Also fixed the position, considered individual margin and font size from each element of a certain row

**Comment by anxuae** [comment]
> @anxuae created `max_char` on label to create a multi line text. The only issue here is as lines cannot been selected, the scroll does not work with arrow keys. See scroll example:

nice!

> I suggest to scroll also with re pag / av pag keys. Also, is `mouse_enabled` is False the scroll will not work (as user cannot scroll with keyboard)

ok, I will add it

**Comment by anxuae** [comment]
It is quite strange that the `textwrap` is not done in the `Label` widget. It should be normally the place.
Maybe instead of keeping a dictionary to store values, we should use the set_position and maybe a set_size to store those values in the `_rect` of the widget.

**Comment by anxuae** [comment]
Remove my comment, I did not understand the code . But it is ok ;-)

**Comment by anxuae** [comment]
PAGEUP / DOWN implemented

**Comment by ppizarror** [comment]
> Remove my comment, I did not understand the code . But it is ok ;-)

@anxuae  I saw that comment on email. 1) Label should not textwrap because if wrap more labels are added to the menu. So a widget adding more widgets... I don't know,
2) This solution of position is quite similar to the previous one, the only changes made are:
- Introduced a `self._widgets_position` dict.
- Only when surface is generated, function `_update_widget_position` is called.
- `_update_widget_position` calculates the position of each widget based on it's location through col and rect using indicial methods, adds the alignment, font height and margin. Instead of setting the position on the widget, it's stored in the `self._widgets_position` dict using the id of the widget.
- `draw` method uses the key.

But, as draw also "re sets" the position, the dict is quite useless. So, using your recomendation I removed the dict, so `_update_widget_position()` calculates the position of the rect and update the widget. Now draw is more concise:

```
    def draw(self):
        """
        Draw menu to the active surface.

        :return: None
        """
        # The surface may has been erased because the number
        # of widgets has changed and thus size shall be calculated.
        if not self._widgets_surface:
            self._build_widget_surface()

        # Draw widgets
        self._widgets_surface.fill((255, 255, 255, 0))  # Transparent
        for widget in self._widgets:

            # Draw widget
            widget.draw(self._widgets_surface)

            # If selected item then draw a rectangle
            if self._selection_highlight and widget.selected:
                widget.draw_selected_rect(self._widgets_surface,
                                          self._selection_color,
                                          self._selection_highlight_margin_x,
                                          self._selection_highlight_margin_y,
                                          self._selection_border_width)

        self._scroll.draw(self._surface)
        self._menubar.draw(self._surface)
```

**Pull request merged**
