### PR TITLE
Vfill widget

### PR DESCRIPTION
**Pull request by ppizarror**
- Added new widget ``VFill``, #400.

### CODE REVIEW

**Comment by vnmabus** [comment]
Can you merge the master into this branch, so I can try the code with the border size improvements?

**Comment by ppizarror** [comment]
> Can you merge the master into this branch, so I can try the code with the border size improvements?

Done 💯

**Comment by vnmabus** [comment]
It seems that the width of `VFill` is the same as the width of the original menu. In my case, I adjust the width of the menu to the size of the widgets after they are all created. This worked before no matter what the initial size of the menu was, but if I add `VFill` widgets, I have to set the original width to 1 (0 is not allowed), otherwise the original width is kept.

I think that vertical alignment widgets should always have 0 width (or 1 if that is not supported). I am not sure if that affects other parts of the library.

**Comment by ppizarror** [comment]
Are you resizing the widgets? Because in tests, the following (without any further change) is true:

```python
menu = MenuUtils.generic_menu()
b = menu.add.button('nice')  # Add button
vf1 = menu.add.vertical_fill()
self.assertEqual(vf1.get_width(), 0)
```

**Comment by vnmabus** [comment]
Hum, if I print the size of each widget I obtain:
```
0
196
0
222
0
222
0
222
0
222
0
196
0
248
0
170
0
```
where the 0's are the `VFill` widgets, as expected.

However, `menu.get_size(widget=True)` returns `(625, 717)`! How can that be?

**Comment by ppizarror** [comment]
Can you provide a minimal working example? The following works as expected, thus, I cannot reproduce your issue:

```python
menu = MenuUtils.generic_menu()
b = menu.add.button('nice')  # Add button
bh = b.get_height()
self.assertEqual(menu.get_size(widget=True), b.get_size())

# Now add 1 vfill, this should use all available height
vf1 = menu.add.vertical_fill()
self.assertEqual(vf1.get_width(), 0)
self.assertEqual(menu.get_size(widget=True), (b.get_width(), bh + vf1.get_height()))
```

**Comment by ppizarror** [comment]
> Hum, if I print the size of each widget I obtain:
> 
> ```
> 0
> 196
> 0
> 222
> 0
> 222
> 0
> 222
> 0
> 222
> 0
> 196
> 0
> 248
> 0
> 170
> 0
> ```
> 
> where the 0's are the `VFill` widgets, as expected.
> 
> However, `menu.get_size(widget=True)` returns `(625, 717)`! How can that be?

@vnmabus are you using a column/row layout?

**Comment by vnmabus** [comment]
> @vnmabus are you using a column/row layout?

Nope.

**Comment by ppizarror** [comment]
> > @vnmabus are you using a column/row layout?
> 
> Nope.

Then I need an example. Maybe this widget introduces a bug, or you have spotted a new bug

**Comment by vnmabus** [comment]
The problem DOES NOT OCCUR if I remove `widget_alignment=pygame_menu.locals.ALIGN_LEFT` from the theme. I hope this clarify something for you.

**Comment by vnmabus** [comment]
So, this is a minimal working example:
```python
import pygame
import pygame_menu


pygame.init()
surface = pygame.display.set_mode((800, 600))

theme = pygame_menu.Theme(
    widget_alignment=pygame_menu.locals.ALIGN_LEFT,
)

menu = pygame_menu.Menu(
    "",
    800,
    600,
    center_content=True,
    theme=theme,
)
# Now add 1 vfill, this should use all available height
vf1 = menu.add.vertical_fill()
print(menu.get_size(widget=True))

b = menu.add.button('nice')  # Add button
print(menu.get_size(widget=True), b.get_size())

# Now add 1 vfill, this should use all available height
vf2 = menu.add.vertical_fill()
print(menu.get_size(widget=True), b.get_size())
```

**Comment by ppizarror** [comment]
@vnmabus I've fixed the issue (and added the tests!). The problem was I overwrote ``NoneWidget.set_alignment``, so ``VFill`` (and other) had an incorrect alignment, thus, when calculating the maximum and minimum x position it assumed was centered, so it used the whole container.

Let me know if the issue is fixed :)

**Comment by vnmabus** [comment]
This fixes it, thanks!!

**Comment by ppizarror** [comment]
> This fixes it, thanks!!

I'll merge to master then. Let me know about anything else. If you need, I can publish a new PyPI version

**Comment by vnmabus** [comment]
Can you publish in PyPI? I have to make a PR and need to upgrade the dependency to your package.

**Comment by ppizarror** [comment]
> Can you publish in PyPI? I have to make a PR and need to upgrade the dependency to your package.

Done! See https://github.com/ppizarror/pygame-menu/releases/tag/4.2.7, https://pypi.org/project/pygame-menu/

**Pull request merged**
