### PR TITLE
Text input & all is widget

### PR DESCRIPTION
**Pull request by anxuae**
Hi,

After some weeks, I finally found the time to make this PR.

### Concerning your previous remarks about #8 :

1. The backspace button is now disabled

2. The "word ellipsis" on too long text input is not yet implemented, I will propose it in another PR (because not enough time for the moment)

3. Events from navigation are ignored on a text input

### General remark about the rework that I have performed:

1. All elements of a menu are now a widget.  This implies more custom classes and objects, but it gives the advantage of:

  a. Avoid managing all events in the same function (each widget has its own ``update()`` method)
  b. Going in the way of #18 
  c. Widget position can be moved easily, it will be easier to implement #15 in the future

2. A new attribute ``_top`` has been added to keep reference to the top level menu. However, I think that the management of change between menu (open/close) is quite difficult to manage with the current code (for instance when we need to use the ``_actual``attribute?). Maybe a handler class can be developed to manage the changes between menus.

### Callback management

I have standardize the way to call the callback function. All widget that can receive/change their values (implements the ``get_value()`` method) automatically provide the current value to the ``onreturn`` and ``onchange`` callback as first argument.
This change imply breaking the compatibility with previous version of ``pygame-menu``. Managing callback in such a way, permits to keep constancy between function signature.
I let you decide if this is acceptable for the version ``2.0``.

Fill free to update/change anything.

anxuae

### CODE REVIEW

**Comment by ppizarror** [comment]
Hi I've modified some things but this addition is huge! Thanks for the work
Some things:

- Readme must be updated
- Now menu contains much more inputs (and more in the future), so I think a ```get_input_data()``` method must be done, this can be part of a new PR. This function must check all widgets, retrieve the data that they contains and return a dict object (maybe). The problem now is that actually there is **no** way to identify any input (like #id of HTML), so I think all the inputs must have an identification, mandatory, that have to be implemented, if no ID provided it can be generated (using some getUUID function around there). This should be part of v2.0 because this can lead to a major compatibility issue

```
menu.get_input_data() # the name can change
=>
{"text-id-1": "hi",
"selector-id-1": 0, # the selected index
"text-id-2": ""
}
```

**Comment by ppizarror** [comment]
The id definition can be an input of ```Widget``` abstract class, maybe:

```
class Widget(object):
    """
    Widget abstract class.
    """

    def __init__(self,
                  id="",
                 onchange=None,
                 onreturn=None,
                 args=None,
                 kwargs=None
                 ):
         if id=="": id = generateUUID() # Or throw an exception... i dont know 🤔 
```

**Comment by ppizarror** [comment]
```widget.get_id()``` can be also a method, or ID can be private for each widget (thinking about security)

**Comment by ppizarror** [comment]
Added an optional parameter named ```maxlength```, It works but does not notify to user that he has reached the limit, maybe changing the color of the text, momentaneously, can be a mechanism to advice

**Comment by ppizarror** [comment]
I've implemented the text-overflow with ellipsis based on your code, can you check if there's any error? I found quite difficult to implement it so I had to modify some of your widget

**Comment by anxuae** [comment]
It's working great! very good job.
Note that I removed ``_pygame.KEYDOWN`` from the last condition in ``update()`` because it has no effect: events with ``_pygame.KEYDOWN`` are already processed in first part of the condition.

**Comment by anxuae** [comment]
Small change, because we need to recalculate widget size before setting its position.
The position is calculated before ``_render()`` call in ``widget.draw()``.

**Comment by anxuae** [comment]
> * Now menu contains much more inputs (and more in the future), so I think a `get_input_data()` method must be done, this can be part of a new PR. This function must check all widgets, retrieve the data that they contains and return a dict object (maybe). The problem now is that actually there is **no** way to identify any input (like #id of HTML), so I think all the inputs must have an identification, mandatory, that have to be implemented, if no ID provided it can be generated (using some getUUID function around there). This should be part of v2.0 because this can lead to a major compatibility issue

Ok for a new PR on that topic. There is in fact two solutions:

1. generate an UUID automatically by the Widget base class using the ``uuid `` lib (no need to pass it in the arguments, this avoid user duplicate). And all methods `Menu.add_...` will return this UUID.
2.  all methods `Menu.add_...` return the widget itself, the user application can keep the list of created widgets and call ``widget.get_value()`` on each one that he need the data.

I prefer the second method because it is more OOP and pythonic, but I let you choose.

**Comment by anxuae** [comment]
I don't know if the files ``readme.json``, ``readme.content.md``and ``README.rst``have to be updated (don't know the purpose of them).

**Comment by anxuae** [comment]
Still one bug investigation, the button ``Close Menu``in ``example.py`` does not close the menu.
Same problem with the arrow button on top-right corner if ``onclose=PYGAME_MENU_CLOSE`` on main menu.

**Comment by ppizarror** [comment]
> I don't know if the files `readme.json`, `readme.content.md`and `README.rst`have to be updated (don't know the purpose of them).

`README.rst` is a small readme for PyPi, `readme.content.md` is the main readme that must be updated, and along with `readme.json` it's converted to `README.md` using the app [readme-generator](https://github.com/ppizarror/readme-generator)

**Comment by ppizarror** [comment]
> > * Now menu contains much more inputs (and more in the future), so I think a `get_input_data()` method must be done, this can be part of a new PR. This function must check all widgets, retrieve the data that they contains and return a dict object (maybe). The problem now is that actually there is **no** way to identify any input (like #id of HTML), so I think all the inputs must have an identification, mandatory, that have to be implemented, if no ID provided it can be generated (using some getUUID function around there). This should be part of v2.0 because this can lead to a major compatibility issue
> 
> Ok for a new PR on that topic. There is in fact two solutions:
> 
> 1. generate an UUID automatically by the Widget base class using the `uuid ` lib (no need to pass it in the arguments, this avoid user duplicate). And all methods `Menu.add_...` will return this UUID. This UUID can be used then to get data using the method `get_input_data()`.
> 2. all methods `Menu.add_...` return the widget itself, the user application can keep the list of created widgets and call `widget.get_value()` on each one that he need the data. In this case the method `update_selector()`could be removed.
> 
> I prefer the second method because it is more OOP and pythonic, but I let you choose.

I think both solutions are good, but I'm thinking in the future to create some kind of "form menu", by now I'll add "id" identificator, if it's no provided `uuid` will be used. By now it does not have any practical usage than `get_input_data()`, but I still believe that this could be potentially useful somehow. Anyway adding 'id' does not break any compatibility

**Comment by ppizarror** [comment]
> Still one bug investigation, the button `Close Menu`in `example.py` does not close the menu.
> Same problem with the arrow button on top-right corner if `onclose=PYGAME_MENU_CLOSE` on main menu.

Ohmm, this needs to be patched

**Comment by ppizarror** [comment]
I've found the bug, when you add a widget you pass the menu behaviour instead of the "element" function as-is, for example:

example.py:
`timer_menu.add_option('Close Menu', PYGAME_MENU_CLOSE)`

That button widget should close the menu, but `timer_menu` has `onclose=PYGAME_MENU_RESET`, so when you add that button: `widget = _widgets.Button(element_name, None, self._close, False)` is executed, but `self._close` calls `PYGAME_MENU_RESET` instead of `PYGAME_MENU_CLOSE`

**Comment by anxuae** [comment]
> `README.rst` is a small readme for PyPi, `readme.content.md` is the main readme that must be updated, and along with `readme.json` it's converted to `README.md` using the app [readme-generator](https://github.com/ppizarror/readme-generator)

Ok, I did not know about the readme-generator app. Sorry I modified  the wrong file.

**Comment by anxuae** [comment]
> That button widget should close the menu, but `timer_menu` has `onclose=PYGAME_MENU_RESET`, so when you add that button: `widget = _widgets.Button(element_name, None, self._close, False)` is executed, but `self._close` calls `PYGAME_MENU_RESET` instead of `PYGAME_MENU_CLOSE`

So what is the priority if a button on the menu say ``close`` but menu say ``instead of close, do a reset``?
For me it seems to be ok, the behavior on the master version is less logical.
However an other bug is present:

https://github.com/ppizarror/pygame-menu/pull/35/commits/d4cc284e6f3323a9f159fb61cbe90c9932e9a583/pygameMenu/menu.py#L491-L493

**Comment by ppizarror** [comment]
> if close:
>             self._top.disable(closelocked)
>         return close

So that solves the problem? Could you push a commit?

**Comment by anxuae** [comment]
Yes the problem is solved

**Comment by ppizarror** [comment]
I'll merge this, any addition please make a new PR
Thanks a lot!

**Pull request merged**
