### PR TITLE
Convert all str.format() instances to f-strings

### PR DESCRIPTION
**Pull request by eforgacs**

### CODE REVIEW

**Comment by mrkprdo** [comment]
Hi, just curious what's the reason behind this change?

**Comment by ppizarror** [comment]
> Hi, just curious what's the reason behind this change?

Hi, I think fstrings are way more reliable than str.format, but this does not affect the library performance

**Comment by eforgacs** [comment]
Believe it or not, they're not only more readable, but they're also a lot faster than both %-formatting and str.format().

Check it out! https://realpython.com/python-f-strings/

**Comment by ppizarror** [comment]
@eforgacs let me know when you've finished converting all files for merging, thanks!!

**Comment by eforgacs** [comment]
> @eforgacs let me know when you've finished converting all files for merging, thanks!!

I believe this should be all of them - used a CLI tool called flynt and it converted them all at once.

**Comment by ppizarror** [comment]
Woah, nice. I will use it to convert my other projects.

The era of ``.format()`` has come to an end. Thanks!

**Pull request merged**
