### PR TITLE
Added mouse handling to TextInput, new style of constants

### PR DESCRIPTION
**Pull request by ppizarror**
Now cursor can be updated with mouse clicks. Also if widget is not selected the mouse click from Menu event is passed to all widgets (if collided)

### CODE REVIEW

**Comment by ppizarror** [comment]
This is a major change, now locals and events are different. I think that now there's a clear difference between local and events. All examples have been changed.

Then:
```
about_menu.add_line(PYGAMEMENU_TEXT_NEWLINE)
about_menu.add_option('Return to menu', PYGAME_MENU_BACK)
```

Now:
```
about_menu.add_line(pygameMenu.locals.PYGAMEMENU_TEXT_NEWLINE)
about_menu.add_option('Return to menu', pygameMenu.events.PYGAME_MENU_BACK)
```

With this change we can introduce many more events and locals, so the user can differentiate them very easilily

Let me know if you have any comments.

**Comment by anxuae** [comment]
Whaou, you make a big job!
Move PymenuAction in a dedicated module is more understandable.

As compatibility with v1.x is completely broken, what do you think about removing ``add_selector_change`` and ``add_selector_return``? I don't think that they have a big interest.
And currently, there is a bug with passed ``kwargs``.

**Comment by ppizarror** [comment]
> Whaou, you make a big job!
> Move PymenuAction in a dedicated module is more understandable.
> 
> As compatibility with v1.x is completely broken, what do you think about removing `add_selector_change` and `add_selector_return`? I don't think that they have a big interest.
> And currently, there is a bug with passed `kwargs`.

Yes, let's remove both functions.
What's the bug?
Feel free to push any commits to this PR

**Comment by anxuae** [comment]
If you keep ``add_selector_change`` and ``add_selector_return``, you need to change:
```
        return self.add_selector(title=title, values=values, onchange=fun,
                                 onreturn=None, kwargs=kwargs)
```
into
```
        return self.add_selector(title=title, values=values, onchange=fun,
                                 onreturn=None, kwargs=kwargs)
``` 

But if you remove them, no more bug

**Comment by ppizarror** [comment]
> If you keep `add_selector_change` and `add_selector_return`, you need to change:
> 
> ```
>         return self.add_selector(title=title, values=values, onchange=fun,
>                                  onreturn=None, kwargs=kwargs)
> ```
> 
> into
> 
> ```
>         return self.add_selector(title=title, values=values, onchange=fun,
>                                  onreturn=None, **kwargs)
> ```
> 
> But if you remove them, no more bug

Deleted, even we weren't using that methods in example files

**Pull request merged**
