### PR TITLE
Add cursor size for text input

### PR DESCRIPTION
**Pull request by mrkprdo**
I am working on textinput for small screens, while i am using textinput font size 15, the cursor is not following the size.
Hence added an option to declare cursor size.

### CODE REVIEW

**Comment by ppizarror** [comment]
I've added some tests, and fixed some typing issues. Thanks :)

**Comment by ppizarror** [comment]
I was wondering why ``cursor_size`` must be in ``*args`` rather than ``**kwargs``. As you can see, most of the ``**kwargs`` parameters modify the style of each widget

**Comment by mrkprdo** [comment]
I thought of that too. But considering in type_input class, most if not all `cursor_*` styling are in args.
If you think this as otherwise, you can go ahead and change it. :)

**Comment by ppizarror** [comment]
yep, maybe in further versions of this gui the parameters could me moved to kwargs, anyway it does not break any compatibility,
thanks

**Comment by ppizarror** [comment]
the new version 4.0.2 will be published today

**Comment by mrkprdo** [comment]
Awesome. Thanks

**Pull request merged**
