### PR TITLE
Refactor duplicate check_key_pressed_valid method into utils module.

### PR DESCRIPTION
**Pull request by eforgacs**

### CODE REVIEW

**Comment by eforgacs** [comment]
#103

**Comment by ppizarror** [comment]
As for now, this is the only refactorizable method you found in the code?

**Comment by eforgacs** [comment]
Well I wanted to start small, and add more as I go. I figured this might be a good start.

**Comment by ppizarror** [comment]
> Well I wanted to start small, and add more as I go. I figured this might be a good start.

thanks!

**Pull request merged**
