### PR TITLE
Add blink functionality, and extract parent class ArrowSelection for LeftArrowSelection and RightArrowSelection.

### PR DESCRIPTION
**Pull request by eforgacs**
Extract parent class ArrowSelection for LeftArrowSelection and RightArrowSelection.

### CODE REVIEW

**Comment by ppizarror** [comment]
This will contain the blinking, or blink will be on another PR?

**Comment by eforgacs** [comment]
I think I'll put the blinking in another PR if that's okay.

**Comment by ppizarror** [comment]
> I think I'll put the blinking in another PR if that's okay.

No worries! :) let's use this PR for all
thanks!!

**Comment by eforgacs** [comment]
SGTM!

**Comment by ppizarror** [comment]
Refactored the main classes, also resets the cursor if the current widget have changed

**Comment by ppizarror** [comment]
I need to merge this as I'll change some things. Any other issue or feature please create a new PR! thanks!

**Comment by eforgacs** [comment]
> I need to merge this as I'll change some things. Any other issue or feature please create a new PR! thanks!

My pleasure! Thank you as well!

**Pull request merged**
